# Using the same code as before, please solve the following exercises
    1. Change the number of observations to 100,000 and see what happens.
    2. Play around with the learning rate. Values like 0.0001, 0.001, 0.1, 1 are all interesting to observe. 
    3. Change the loss function. An alternative loss for regressions is the Huber loss. 
    The Huber loss is more appropriate than the L2-norm when we have outliers, as it is less sensitive to them (in our example we don't have outliers, but you will surely stumble upon a dataset with outliers in the future). The L2-norm loss puts all differences *to the square*, so outliers have a lot of influence on the outcome. 
    The proper syntax of the Huber loss is 'huber_loss'
    
    
Useful tip: When you change something, don't forget to RERUN all cells. This can be done easily by clicking:
Kernel -> Restart & Run All
If you don't do that, your algorithm will keep the OLD values of all parameters.

You can either use this file for all the exercises, or check the solutions of EACH ONE of them in the separate files we have provided. All other files are solutions of each problem. If you feel confident enough, you can simply change values in this file. Please note that it will be nice, if you return the file to starting position after you have solved a problem, so you can use the lecture as a basis for comparison.

## Import the relevant libraries

In [1]:
# We must always import the relevant libraries for our problem at hand. NumPy and TensorFlow are required for this example.
import numpy as np
import matplotlib.pyplot as plt
import tensorflow as tf

## Data generation

We generate data using the exact same logic and code as the example from the previous notebook. The only difference now is that we save it to an npz file. Npz is numpy's file type which allows you to save numpy arrays into a single .npz file. We introduce this change because in machine learning most often: 

* you are given some data (csv, database, etc.)
* you preprocess it into a desired format (later on we will see methods for preprocesing)
* you save it into npz files (if you're working in Python) to access later

Nothing to worry about - this is literally saving your NumPy arrays into a file that you can later access, nothing more.

In [2]:
# First, we should declare a variable containing the size of the training set we want to generate.
observations = 1000

# We will work with two variables as inputs. You can think about them as x1 and x2 in our previous examples.
# We have picked x and z, since it is easier to differentiate them.
# We generate them randomly, drawing from an uniform distribution. There are 3 arguments of this method (low, high, size).
# The size of xs and zs is observations x 1. In this case: 1000 x 1.
xs = np.random.uniform(low=-10, high=10, size=(observations,1))
zs = np.random.uniform(-10, 10, (observations,1))

# Combine the two dimensions of the input into one input matrix. 
# This is the X matrix from the linear model y = x*w + b.
# column_stack is a Numpy method, which combines two matrices (vectors) into one.
generated_inputs = np.column_stack((xs,zs))

# We add a random small noise to the function i.e. f(x,z) = 2x - 3z + 5 + <small noise>
noise = np.random.uniform(-1, 1, (observations,1))

# Produce the targets according to our f(x,z) = 2x - 3z + 5 + noise definition.
# In this way, we are basically saying: the weights should be 2 and -3, while the bias is 5.
generated_targets = 2*xs - 3*zs + 5 + noise

# save into an npz file called "TF_intro"
np.savez('data/TF_intro', inputs=generated_inputs, targets=generated_targets)

## Solving with TensorFlow

<i/>Note: This intro is just the basics of TensorFlow which has way more capabilities and depth than that.<i>

In [3]:
# Load the training data from the NPZ
training_data = np.load('data/TF_intro.npz')

In [4]:
# Declare a variable where we will store the input size of our model
# It should be equal to the number of variables you have
input_size = 2
# Declare the output size of the model
# It should be equal to the number of outputs you've got (for regressions that's usually 1)
output_size = 1

# Outline the model
# We lay out the model in 'Sequential'
# Note that there are no calculations involved - we are just describing our network
model = tf.keras.Sequential([
                            # Each 'layer' is listed here
                            # The method 'Dense' indicates, our mathematical operation to be (xw + b)
                            tf.keras.layers.Dense(output_size,
                                                 # there are extra arguments you can include to customize your model
                                                 # in our case we are just trying to create a solution that is 
                                                 # as close as possible to our NumPy model
                                                 kernel_initializer=tf.random_uniform_initializer(minval=-0.1, maxval=0.1),
                                                 bias_initializer=tf.random_uniform_initializer(minval=-0.1, maxval=0.1)
                                                 )
                            ])

# We can also define a custom optimizer, where we can specify the learning rate
custom_optimizer = tf.keras.optimizers.SGD(learning_rate=0.02)
# Note that sometimes you may also need a custom loss function 
# That's much harder to implement and won't be covered in this course though

# 'compile' is the place where you select and indicate the optimizers and the loss
model.compile(optimizer=custom_optimizer, loss='mean_squared_error')

# finally we fit the model, indicating the inputs and targets
# if they are not otherwise specified the number of epochs will be 1 (a single epoch of training), 
# so the number of epochs is 'kind of' mandatory, too
# we can play around with verbose; we prefer verbose=2
model.fit(training_data['inputs'], training_data['targets'], epochs=100, verbose=2)

Epoch 1/100
32/32 - 0s - loss: 22.7337
Epoch 2/100
32/32 - 0s - loss: 1.2338
Epoch 3/100
32/32 - 0s - loss: 0.4466
Epoch 4/100
32/32 - 0s - loss: 0.4155
Epoch 5/100
32/32 - 0s - loss: 0.3963
Epoch 6/100
32/32 - 0s - loss: 0.3749
Epoch 7/100
32/32 - 0s - loss: 0.3974
Epoch 8/100
32/32 - 0s - loss: 0.4217
Epoch 9/100
32/32 - 0s - loss: 0.3949
Epoch 10/100
32/32 - 0s - loss: 0.4133
Epoch 11/100
32/32 - 0s - loss: 0.3724
Epoch 12/100
32/32 - 0s - loss: 0.4478
Epoch 13/100
32/32 - 0s - loss: 0.4088
Epoch 14/100
32/32 - 0s - loss: 0.3735
Epoch 15/100
32/32 - 0s - loss: 0.4056
Epoch 16/100
32/32 - 0s - loss: 0.3891
Epoch 17/100
32/32 - 0s - loss: 0.3762
Epoch 18/100
32/32 - 0s - loss: 0.3927
Epoch 19/100
32/32 - 0s - loss: 0.3862
Epoch 20/100
32/32 - 0s - loss: 0.4120
Epoch 21/100
32/32 - 0s - loss: 0.3976
Epoch 22/100
32/32 - 0s - loss: 0.3663
Epoch 23/100
32/32 - 0s - loss: 0.3696
Epoch 24/100
32/32 - 0s - loss: 0.3929
Epoch 25/100
32/32 - 0s - loss: 0.4171
Epoch 26/100
32/32 - 0s - loss: 0

## Extract the weights and bias
Extracting the weight(s) and bias(es) of a model is not an essential step for the machine learning process. In fact, usually they would not tell us much in a deep learning context. However, this simple example was set up in a way, which allows us to verify if the answers we get are correct.

In [5]:
# Extracting the weights and biases is achieved quite easily
model.layers[0].get_weights()

[array([[ 1.998011 ],
        [-3.0871801]], dtype=float32),
 array([4.989345], dtype=float32)]

In [6]:
# We can save the weights and biases in separate variables for easier examination
# Note that there can be hundreds or thousands of them!
weights = model.layers[0].get_weights()[0]
weights

array([[ 1.998011 ],
       [-3.0871801]], dtype=float32)

In [7]:
# We can save the weights and biases in separate variables for easier examination
# Note that there can be hundreds or thousands of them!
bias = model.layers[0].get_weights()[1]
bias

array([4.989345], dtype=float32)

## Extract the outputs (make predictions)
Once more, this is not an essential step, however, we usually want to be able to make predictions.

In [8]:
# We can predict new values in order to actually make use of the model
# Sometimes it is useful to round the values to be able to read the output
# Usually we use this method on NEW DATA, rather than our original training data
model.predict_on_batch(training_data['inputs']).round(1)

array([[ 10.3],
       [ 15.5],
       [ -2.9],
       [ -3.3],
       [-17.7],
       [ 17.9],
       [ 32.3],
       [-41.3],
       [-13.6],
       [ 23.4],
       [  9.5],
       [  4.7],
       [ 32.5],
       [ 35.2],
       [ -7.6],
       [ 14.3],
       [ 14.7],
       [  8.9],
       [-14.3],
       [  0.2],
       [-19. ],
       [-31. ],
       [-16.4],
       [ 15.2],
       [ 14.5],
       [  1.5],
       [ 47.1],
       [  5.6],
       [ 25.6],
       [ 33.9],
       [ 14.4],
       [ -5.2],
       [ -4.7],
       [ -8.6],
       [  0.3],
       [  9.1],
       [ -3.5],
       [ -9.5],
       [ -4. ],
       [ -6.1],
       [  0.4],
       [  0.1],
       [  3.4],
       [ 30.6],
       [  3.3],
       [ 45.3],
       [ 39.8],
       [ 18.4],
       [ 28.1],
       [-26.7],
       [  3.8],
       [-15.1],
       [ 14.1],
       [-25.7],
       [ -0.6],
       [  0.1],
       [-22.5],
       [-18.5],
       [  8.4],
       [-26.1],
       [ 21.4],
       [-12.1],
       [

In [9]:
# If we display our targets (actual observed values), we can manually compare the outputs and the targets
training_data['targets'].round(1)

array([[ 10.6],
       [ 16.1],
       [ -2.9],
       [ -2.5],
       [-17.3],
       [ 18. ],
       [ 32.5],
       [-40.6],
       [-12.2],
       [ 22.9],
       [  9.3],
       [  4.3],
       [ 32.3],
       [ 35.6],
       [ -6.7],
       [ 13.6],
       [ 13.2],
       [  9.3],
       [-14.4],
       [ -0.5],
       [-18. ],
       [-30.6],
       [-16.6],
       [ 14.2],
       [ 13.2],
       [  2.1],
       [ 46. ],
       [  5.6],
       [ 25.5],
       [ 32.7],
       [ 14.3],
       [ -3.3],
       [ -4.2],
       [ -8.7],
       [  1.3],
       [  9.5],
       [ -4.3],
       [ -9.2],
       [ -4.8],
       [ -7. ],
       [  0.7],
       [  0.3],
       [  4.6],
       [ 29.2],
       [  2.4],
       [ 44. ],
       [ 39.4],
       [ 17.1],
       [ 27.9],
       [-26.7],
       [  3. ],
       [-14.3],
       [ 13.8],
       [-24. ],
       [ -1.9],
       [ -1. ],
       [-21.6],
       [-18.7],
       [  7.7],
       [-25.7],
       [ 20.6],
       [-12.5],
       [

## Plotting the data

In [10]:
# The model is optimized, so the outputs are calculated based on the last form of the model

# We have to np.squeeze the arrays in order to fit them to what the plot function expects.
# Doesn't change anything as we cut dimensions of size 1 - just a technicality.
plt.plot(np.squeeze(model.predict_on_batch(training_data['inputs'])), np.squeeze(training_data['targets']))
plt.xlabel('outputs')
plt.ylabel('targets')
plt.show()

# Voila - what you see should be exactly the same as in the previous notebook!
# You probably don't see the point of TensorFlow now - it took us the same number of lines of code
# to achieve this simple result. However, once we go deeper in the next chapter,
# TensorFlow will save us hundreds of lines of code.